# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /Dockerfile.tmpl.php

# https://hub.docker.com/_/debian
FROM debian:buster-slim
LABEL Luc Appelman "lucapppelman@gmail.com"

# Build and install OpenDKIM
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends --no-install-suggests \
                inetutils-syslogd \
                ca-certificates \
    && update-ca-certificates \
    # Install OpenDKIM dependencies
    && apt-get install -y --no-install-recommends --no-install-suggests \
                opendkim \
    # Cleanup unnecessary stuff
    && apt-get purge -y --auto-remove \
                -o APT::AutoRemove::RecommendsImportant=false \
                $toolDeps $buildDeps \
    && rm -rf /var/lib/apt/lists/* \
            /etc/*/inetutils-syslogd \
            /tmp/*

# Install s6-overlay
RUN apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests curl \
    && curl -fL -o /tmp/s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v2.0.0.1/s6-overlay-amd64.tar.gz \
    && tar -xzf /tmp/s6-overlay.tar.gz -C / \
    # Cleanup unnecessary stuff
    && apt-get purge -y --auto-remove \
                -o APT::AutoRemove::RecommendsImportant=false \
                curl \
    && rm -rf /var/lib/apt/lists/* \
            /tmp/*

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
    S6_CMD_WAIT_FOR_SERVICES=1

COPY rootfs /

RUN chmod +x /etc/services.d/*/run \
            /etc/cont-init.d/*

EXPOSE 8891

WORKDIR /etc/opendkim

VOLUME /etc/ssl/dkim

STOPSIGNAL SIGTERM

ENTRYPOINT ["/init"]

CMD ["opendkim", "-f", "-D"]